#!/bin/bash

set -euo pipefail

# ====== 1. Application constants and defaults ================================

readonly APP_NAME="obsidian-vault-backup"
readonly SCRIPT_VERSION="1.0.0"
readonly PROJECT_URL="https://github.com/Ax51/obsidian-valut-backup"
readonly SHELL_COMMAND_NAME="obsidian-backup"
readonly SYSTEM_USER="$(id -un)"
readonly APP_DIR="$HOME/.config/$APP_NAME"
readonly SETTINGS_FILE="$APP_DIR/settings.sh"
readonly KOPIA_CONFIG_FILE="$APP_DIR/repository.config"
readonly LOG_FILE="$APP_DIR/backup.log"
readonly STATE_FILE="$APP_DIR/state.sh"
readonly LOCK_DIR="$APP_DIR/backup.lock"
readonly INSTALLED_SCRIPT="$APP_DIR/$APP_NAME.sh"
readonly LAUNCHD_LABEL="com.$SYSTEM_USER.obsidian-vault-backup"
readonly LAUNCHD_PLIST="$HOME/Library/LaunchAgents/$LAUNCHD_LABEL.plist"
readonly KEYCHAIN_SERVICE="$LAUNCHD_LABEL.kopia"
readonly KEYCHAIN_ACCOUNT="repository-password"
readonly DEFAULT_REMOTE_NAME="mega"
readonly DEFAULT_REMOTE_PATH="ObsidianVaultBackup"
readonly DEFAULT_SCHEDULE_TIME="03:00"
readonly DEFAULT_SOAK_MINUTES=10
readonly SOURCE_QUIET_SECONDS=60
readonly SOURCE_QUIET_MAX_ATTEMPTS=5
readonly REMOTE_RETRY_SECONDS=30
readonly REMOTE_MAX_ATTEMPTS=10

SOURCE_PATH=""
REMOTE_NAME="$DEFAULT_REMOTE_NAME"
REMOTE_PATH="$DEFAULT_REMOTE_PATH"
MEGA_EMAIL=""
SCHEDULE_TIME="$DEFAULT_SCHEDULE_TIME"
SOAK_MINUTES="$DEFAULT_SOAK_MINUTES"
KOPIA_BIN=""
RCLONE_BIN=""
DISCLAIMER_ACCEPTED=false
DISCLAIMER_ACCEPTED_AT=""
SHELL_COMMAND_OFFERED=false

CLI_SOURCE_PATH=""
IMMEDIATE_BACKUP=true
UPDATE_SETTINGS=false
INSTALL_SCHEDULE=true
VERIFY_AFTER_BACKUP=false
INSPECT_STATUS=false
RESTORE_MODE=false
RESTORE_STAGING_DIR=""
SCHEDULED_RUN=false
FIRST_CONFIGURATION=false
REPOSITORY_CONNECTION_CHANGED=false


# ====== 2. Output, prompts, and validation ====================================

info() {
  printf '\n%s\n' "$*"
}

success() {
  printf '✓ %s\n' "$*"
}

warn() {
  printf 'Warning: %s\n' "$*" >&2
}

die() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

prompt_value() {
  local prompt="$1"
  local default_value="${2:-}"
  local answer=""

  if [[ -n "$default_value" ]]; then
    printf '%s [%s]: ' "$prompt" "$default_value" >&2
  else
    printf '%s: ' "$prompt" >&2
  fi
  IFS= read -r answer || die "Input stream closed before an answer was provided."
  printf '%s' "${answer:-$default_value}"
}

prompt_secret() {
  local prompt="$1"
  local answer=""
  printf '%s: ' "$prompt" >&2
  IFS= read -r -s answer || die "Input stream closed before a secret was provided."
  printf '\n' >&2
  printf '%s' "$answer"
}

confirm() {
  local prompt="$1"
  local answer=""
  printf '%s [y/N]: ' "$prompt" >&2
  IFS= read -r answer || die "Input stream closed before an answer was provided."
  case "$answer" in
    y|Y|yes|YES) return 0 ;;
    *) return 1 ;;
  esac
}

show_disclaimer_and_confirm() {
  cat <<EOF

==============================================================================
IMPORTANT — READ BEFORE CONTINUING
==============================================================================

This is experimental, development-stage backup software provided as-is,
without warranties or guarantees of any kind.

Depending on the selected options, this script may:

  • install Homebrew, Kopia, rclone, and KopiaUI;
  • create files under $APP_DIR;
  • update rclone's standard configuration with your MEGA credentials;
  • store a Kopia repository password in macOS Keychain;
  • create $LAUNCHD_PLIST;
  • optionally create a $SHELL_COMMAND_NAME symlink in Homebrew's bin directory;
  • create encrypted backup data in your configured MEGA account;
  • read every file inside the source directory you select; and
  • in explicit restore mode, write files into the selected source directory.

Backup mode is intended to read, not modify, the selected source directory.
Restore mode intentionally writes to it only after a separate confirmation.
Backup and restore software can cause data loss when configured or used
incorrectly. Test it with disposable data and verify a full restore before
using it with important files.

By continuing, you confirm that you have read the project documentation,
understand what the script does, accept all associated risks, and agree that
the author and contributors are not responsible for data loss, service costs,
account issues, security incidents, or any other damage resulting from its use.

Documentation:
$PROJECT_URL

EOF

  confirm "Do you understand and want to continue?" || {
    printf 'Cancelled. No setup or backup actions were performed.\n'
    exit 0
  }
}

record_disclaimer_acceptance() {
  mkdir -p "$APP_DIR"
  chmod 700 "$APP_DIR"
  umask 077

  DISCLAIMER_ACCEPTED=true
  DISCLAIMER_ACCEPTED_AT="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

  if [[ -f "$SETTINGS_FILE" ]]; then
    {
      printf 'DISCLAIMER_ACCEPTED=true\n'
      printf 'DISCLAIMER_ACCEPTED_AT=%q\n' "$DISCLAIMER_ACCEPTED_AT"
    } >> "$SETTINGS_FILE"
  else
    {
      printf '# Generated by %s. Do not add passwords to this file.\n' "$APP_NAME"
      printf 'DISCLAIMER_ACCEPTED=true\n'
      printf 'DISCLAIMER_ACCEPTED_AT=%q\n' "$DISCLAIMER_ACCEPTED_AT"
    } > "$SETTINGS_FILE"
  fi

  chmod 600 "$SETTINGS_FILE"
  success "Disclaimer acceptance saved to $SETTINGS_FILE"
}

ensure_disclaimer_acceptance() {
  [[ "$DISCLAIMER_ACCEPTED" == true ]] && return 0

  if [[ "$SCHEDULED_RUN" == true ]]; then
    die "Disclaimer acceptance is missing. Run the script manually first."
  fi

  show_disclaimer_and_confirm
  record_disclaimer_acceptance
}

expand_home() {
  local value="$1"
  case "$value" in
    '~') printf '%s' "$HOME" ;;
    '~/'*) printf '%s/%s' "$HOME" "${value#\~/}" ;;
    *) printf '%s' "$value" ;;
  esac
}

decode_path_input() {
  local value="$1"
  local decoded=""
  local character=""
  local index=0
  local length=0

  case "$value" in
    \"*\") value="${value#\"}"; value="${value%\"}" ;;
    \'*\') value="${value#\'}"; value="${value%\'}" ;;
  esac

  length=${#value}
  while (( index < length )); do
    character="${value:index:1}"
    if [[ "$character" == '\' && $((index + 1)) -lt length ]]; then
      index=$((index + 1))
      character="${value:index:1}"
    fi
    decoded="${decoded}${character}"
    index=$((index + 1))
  done

  printf '%s' "$decoded"
}

normalize_existing_directory() {
  local input_path="$1"
  local expanded_path=""

  input_path="$(decode_path_input "$input_path")"
  expanded_path="$(expand_home "$input_path")"
  [[ -d "$expanded_path" ]] || return 1
  (cd "$expanded_path" 2>/dev/null && pwd -P)
}

validate_remote_name() {
  [[ "$1" =~ ^[A-Za-z0-9_-]+$ ]] || die \
    "Remote name may contain only letters, numbers, underscores, and hyphens."
}

validate_schedule_time() {
  [[ "$1" =~ ^([01][0-9]|2[0-3]):[0-5][0-9]$ ]] || die \
    "Schedule time must use 24-hour HH:MM format."
}

validate_soak_minutes() {
  [[ "$1" =~ ^[0-9]+$ ]] || die "Soak time must be a number of minutes."
  (( "$1" <= 60 )) || die "Soak time cannot exceed 60 minutes."
}

usage() {
  cat <<'EOF'
Obsidian Vault Backup for macOS

Usage:
  ./obsidian-vault-backup.sh [options]

Options:
  --source PATH          Use PATH as the source for this run only.
  --no-immediate-backup  Configure everything without starting a backup now.
  --no-schedule          Do not install or update the launchd schedule.
  --update-settings      Interactively update saved settings and credentials.
  --verify               Verify 100% of snapshot files after the backup.
  --restore              Restore from the latest snapshot into the saved source.
  --inspect              Show configuration and schedule status without changes.
  --version              Show the script version.
  -h, --help             Show this help.

Saved settings and the installed script live in:
  ~/.config/obsidian-vault-backup

Examples:
  ./obsidian-vault-backup.sh
  ./obsidian-vault-backup.sh --no-immediate-backup
  ./obsidian-vault-backup.sh --source /tmp/TestVault --no-schedule
  ./obsidian-vault-backup.sh --update-settings
  ./obsidian-vault-backup.sh --restore
  ./obsidian-vault-backup.sh --inspect
EOF
  printf '\nFull documentation:\n  %s\n' "$PROJECT_URL"
}


# ====== 3. Command-line arguments ============================================

parse_arguments() {
  while (($#)); do
    case "$1" in
      --source)
        (($# >= 2)) || die "--source requires a path."
        CLI_SOURCE_PATH="$2"
        shift 2
        ;;
      --no-immediate-backup)
        IMMEDIATE_BACKUP=false
        shift
        ;;
      --no-schedule)
        INSTALL_SCHEDULE=false
        shift
        ;;
      --update-settings)
        UPDATE_SETTINGS=true
        shift
        ;;
      --verify)
        VERIFY_AFTER_BACKUP=true
        shift
        ;;
      --restore)
        RESTORE_MODE=true
        IMMEDIATE_BACKUP=false
        INSTALL_SCHEDULE=false
        shift
        ;;
      --inspect)
        INSPECT_STATUS=true
        shift
        ;;
      --scheduled-run)
        SCHEDULED_RUN=true
        INSTALL_SCHEDULE=false
        shift
        ;;
      --version)
        printf '%s %s\n' "$APP_NAME" "$SCRIPT_VERSION"
        exit 0
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "Unknown option: $1. Run with --help to see available options."
        ;;
    esac
  done
}

validate_argument_combinations() {
  if [[ "$RESTORE_MODE" == true ]]; then
    [[ "$SCHEDULED_RUN" == false ]] || die "--restore cannot run through launchd."
    [[ "$VERIFY_AFTER_BACKUP" == false ]] || die \
      "--restore cannot be combined with --verify."
    [[ "$INSPECT_STATUS" == false ]] || die \
      "--restore cannot be combined with --inspect."
    [[ "$UPDATE_SETTINGS" == false ]] || die \
      "Update settings in a separate run before using --restore."
  fi
}


# ====== 4. macOS and Homebrew dependencies ===================================

add_homebrew_to_path() {
  if [[ -x /opt/homebrew/bin/brew ]]; then
    PATH="/opt/homebrew/bin:$PATH"
  elif [[ -x /usr/local/bin/brew ]]; then
    PATH="/usr/local/bin:$PATH"
  fi
  export PATH
}

install_homebrew_if_needed() {
  command -v brew >/dev/null 2>&1 && return 0

  [[ "$SCHEDULED_RUN" == false ]] || die "Homebrew is not installed. Run the script manually first."
  confirm "Homebrew is required to install backup tools. Install it now?" || \
    die "Homebrew is required. Install it from https://brew.sh and run this script again."

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  add_homebrew_to_path
  command -v brew >/dev/null 2>&1 || die \
    "Homebrew was installed but is not on PATH. Restart Terminal and rerun the script."
}

install_cli_tools_if_needed() {
  local missing=()

  command -v kopia >/dev/null 2>&1 || missing+=(kopia)
  command -v rclone >/dev/null 2>&1 || missing+=(rclone)
  ((${#missing[@]} == 0)) && return 0

  [[ "$SCHEDULED_RUN" == false ]] || die \
    "Required utilities are missing: ${missing[*]}. Run the script manually first."

  confirm "Install the missing utilities with Homebrew (${missing[*]})?" || \
    die "Cannot continue without: ${missing[*]}"
  brew install "${missing[@]}"
}

offer_kopia_ui() {
  [[ "$SCHEDULED_RUN" == false ]] || return 0
  [[ "$FIRST_CONFIGURATION" == true ]] || return 0
  [[ -d /Applications/KopiaUI.app || -d "$HOME/Applications/KopiaUI.app" ]] && return 0

  if confirm "Install KopiaUI for visual browsing and restores?"; then
    brew install --cask kopiaui
  else
    warn "KopiaUI was skipped. You can install it later with: brew install --cask kopiaui"
  fi
}

ensure_dependencies() {
  [[ "$(uname -s)" == Darwin ]] || die "This script supports macOS only."
  command -v security >/dev/null 2>&1 || die "macOS security utility was not found."
  command -v curl >/dev/null 2>&1 || die "curl was not found."

  add_homebrew_to_path
  install_homebrew_if_needed
  install_cli_tools_if_needed

  KOPIA_BIN="$(command -v kopia)"
  RCLONE_BIN="$(command -v rclone)"
  offer_kopia_ui
}


# ====== 5. Persistent application files and settings =========================

extract_script_version() {
  local script_file="$1"
  awk -F'"' '$1 == "readonly SCRIPT_VERSION=" { print $2; exit }' "$script_file"
}

valid_script_version() {
  [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
}

version_is_greater() {
  local left="$1"
  local right="$2"
  local index=""
  local left_parts=()
  local right_parts=()

  IFS='.' read -r -a left_parts <<< "$left"
  IFS='.' read -r -a right_parts <<< "$right"

  for index in 0 1 2; do
    if (( left_parts[index] > right_parts[index] )); then
      return 0
    fi
    if (( left_parts[index] < right_parts[index] )); then
      return 1
    fi
  done
  return 1
}

install_script_copy() {
  local source_file="${BASH_SOURCE[0]:-}"
  local source_path=""
  local installed_version="0.0.0"
  local temporary_script="$INSTALLED_SCRIPT.tmp"

  mkdir -p "$APP_DIR"
  chmod 700 "$APP_DIR"

  if [[ -n "$source_file" && -f "$source_file" ]]; then
    source_path="$(cd "$(dirname "$source_file")" && pwd)/$(basename "$source_file")"
    [[ "$source_path" != "$INSTALLED_SCRIPT" ]] || return 0

    if [[ -f "$INSTALLED_SCRIPT" ]]; then
      installed_version="$(extract_script_version "$INSTALLED_SCRIPT")"
      valid_script_version "$installed_version" || installed_version="0.0.0"

      if version_is_greater "$installed_version" "$SCRIPT_VERSION"; then
        die "Refusing to replace installed version $installed_version with older version $SCRIPT_VERSION. Run $INSTALLED_SCRIPT instead."
      fi

      if [[ "$installed_version" == "$SCRIPT_VERSION" ]]; then
        success "Script version $SCRIPT_VERSION is already installed"
        return 0
      fi
    fi

    cp "$source_file" "$temporary_script"
    chmod 700 "$temporary_script"
    mv "$temporary_script" "$INSTALLED_SCRIPT"
    success "Installed script version $SCRIPT_VERSION at $INSTALLED_SCRIPT"
  elif [[ ! -x "$INSTALLED_SCRIPT" ]]; then
    die "Download the script to a file before running it so it can install a persistent copy."
  fi
}

offer_shell_command() {
  local bin_directory="${1:-}"
  local command_path=""
  local existing_command=""

  [[ -n "$bin_directory" ]] || bin_directory="$(brew --prefix)/bin"
  command_path="$bin_directory/$SHELL_COMMAND_NAME"

  if [[ -L "$command_path" && "$(readlink "$command_path")" == "$INSTALLED_SCRIPT" ]]; then
    success "Shell command is available: $SHELL_COMMAND_NAME"
    return 0
  fi

  existing_command="$(command -v "$SHELL_COMMAND_NAME" 2>/dev/null || true)"
  if [[ -n "$existing_command" || -e "$command_path" || -L "$command_path" ]]; then
    warn "Cannot install '$SHELL_COMMAND_NAME': another command already exists at ${existing_command:-$command_path}"
    SHELL_COMMAND_OFFERED=true
    save_settings
    return 0
  fi

  if [[ "$SHELL_COMMAND_OFFERED" == true && "$UPDATE_SETTINGS" == false ]]; then
    return 0
  fi

  printf 'The command will be added as a symlink:\n  %s -> %s\n' \
    "$command_path" "$INSTALLED_SCRIPT"
  if confirm "Install the '$SHELL_COMMAND_NAME' shell command?"; then
    [[ -d "$bin_directory" && -w "$bin_directory" ]] || die \
      "Homebrew bin directory is not writable: $bin_directory"
    ln -s "$INSTALLED_SCRIPT" "$command_path"
    success "Shell command installed: $SHELL_COMMAND_NAME"
    if ! command -v "$SHELL_COMMAND_NAME" >/dev/null 2>&1; then
      warn "The command directory is not on PATH yet. Restart Terminal and try again."
    fi
  else
    warn "Shell command installation skipped. Run with --update-settings to be asked again."
  fi

  SHELL_COMMAND_OFFERED=true
  save_settings
}

load_settings() {
  [[ -f "$SETTINGS_FILE" ]] || return 1
  # The file is generated by this script and readable only by the current user.
  # shellcheck disable=SC1090
  source "$SETTINGS_FILE"
}

save_settings() {
  local temporary_file="$SETTINGS_FILE.tmp"
  umask 077
  {
    printf '# Generated by %s. Do not add passwords to this file.\n' "$APP_NAME"
    printf 'SOURCE_PATH=%q\n' "$SOURCE_PATH"
    printf 'REMOTE_NAME=%q\n' "$REMOTE_NAME"
    printf 'REMOTE_PATH=%q\n' "$REMOTE_PATH"
    printf 'MEGA_EMAIL=%q\n' "$MEGA_EMAIL"
    printf 'SCHEDULE_TIME=%q\n' "$SCHEDULE_TIME"
    printf 'SOAK_MINUTES=%q\n' "$SOAK_MINUTES"
    printf 'DISCLAIMER_ACCEPTED=%q\n' "$DISCLAIMER_ACCEPTED"
    printf 'DISCLAIMER_ACCEPTED_AT=%q\n' "$DISCLAIMER_ACCEPTED_AT"
    printf 'SHELL_COMMAND_OFFERED=%q\n' "$SHELL_COMMAND_OFFERED"
  } > "$temporary_file"
  mv "$temporary_file" "$SETTINGS_FILE"
  chmod 600 "$SETTINGS_FILE"
  success "Settings saved to $SETTINGS_FILE"
  printf '  Repository passwords are stored in macOS Keychain, not in this file.\n'
}

configure_rclone_remote() {
  local mega_password="$1"
  local obscured_password=""
  local remote_exists=false

  "$RCLONE_BIN" listremotes 2>/dev/null | \
    grep -Fxq "${REMOTE_NAME}:" && remote_exists=true

  if [[ -z "$mega_password" ]]; then
    [[ "$remote_exists" == true ]] || die "A MEGA password is required for a new remote."
    "$RCLONE_BIN" config update \
      "$REMOTE_NAME" user "$MEGA_EMAIL" --no-output
  else
    obscured_password="$(printf '%s\n' "$mega_password" | "$RCLONE_BIN" obscure -)"
    if [[ "$remote_exists" == true ]]; then
      "$RCLONE_BIN" config update \
        "$REMOTE_NAME" user "$MEGA_EMAIL" pass "$obscured_password" \
        --no-obscure --no-output
    else
      "$RCLONE_BIN" config create \
        "$REMOTE_NAME" mega user "$MEGA_EMAIL" pass "$obscured_password" \
        --no-obscure --no-output
    fi
  fi
  unset mega_password obscured_password
}

configure_settings_interactively() {
  local old_remote_spec="${REMOTE_NAME}:${REMOTE_PATH}"
  local source_input=""
  local schedule_input=""
  local soak_input=""
  local mega_password=""
  local remote_already_exists=false

  info "Configuration"
  printf 'Settings will be stored in: %s\n' "$SETTINGS_FILE"
  printf 'Your Kopia password will be stored in macOS Keychain.\n'
  printf 'The rclone file contains an obscured (not strongly encrypted) MEGA password and is readable only by your macOS account.\n\n'

  while :; do
    source_input="$(prompt_value "Folder to back up" "$SOURCE_PATH")"
    if SOURCE_PATH="$(normalize_existing_directory "$source_input")"; then
      printf 'Resolved source path: %s\n' "$SOURCE_PATH"
      break
    fi
    warn "Folder does not exist or cannot be resolved: $source_input"
  done

  REMOTE_NAME="$(prompt_value "rclone remote name" "$REMOTE_NAME")"
  validate_remote_name "$REMOTE_NAME"
  REMOTE_PATH="$(prompt_value "Folder in MEGA for the encrypted repository" "$REMOTE_PATH")"
  [[ -n "$REMOTE_PATH" ]] || die "Remote path cannot be empty."
  MEGA_EMAIL="$(prompt_value "MEGA account email" "$MEGA_EMAIL")"
  [[ -n "$MEGA_EMAIL" ]] || die "MEGA email cannot be empty."

  "$RCLONE_BIN" listremotes 2>/dev/null | \
    grep -Fxq "${REMOTE_NAME}:" && remote_already_exists=true
  if [[ "$remote_already_exists" == true ]]; then
    if confirm "Update the saved MEGA password?"; then
      mega_password="$(prompt_secret "MEGA password")"
      [[ -n "$mega_password" ]] || die "MEGA password cannot be empty."
    fi
  else
    mega_password="$(prompt_secret "MEGA password")"
    [[ -n "$mega_password" ]] || die "MEGA password cannot be empty."
  fi

  schedule_input="$(prompt_value "Daily backup time (HH:MM)" "$SCHEDULE_TIME")"
  validate_schedule_time "$schedule_input"
  SCHEDULE_TIME="$schedule_input"

  soak_input="$(prompt_value "Scheduled wake-up soak in minutes" "$SOAK_MINUTES")"
  validate_soak_minutes "$soak_input"
  SOAK_MINUTES="$soak_input"

  configure_rclone_remote "$mega_password"
  unset mega_password
  save_settings
  "$RCLONE_BIN" config file

  if [[ -f "$KOPIA_CONFIG_FILE" && "$old_remote_spec" != "${REMOTE_NAME}:${REMOTE_PATH}" ]]; then
    REPOSITORY_CONNECTION_CHANGED=true
  fi

  if keychain_password >/dev/null 2>&1; then
    if confirm "Replace the Kopia repository password stored in Keychain?"; then
      printf 'This changes only the local Keychain copy; enter the password that the repository already uses.\n'
      prompt_and_store_repository_password
    fi
  fi
}

apply_cli_overrides() {
  if [[ -n "$CLI_SOURCE_PATH" ]]; then
    SOURCE_PATH="$(normalize_existing_directory "$CLI_SOURCE_PATH")" || \
      die "Source folder does not exist or cannot be resolved: $CLI_SOURCE_PATH"
  fi
}

validate_effective_settings() {
  [[ -n "$SOURCE_PATH" ]] || die "Source path is empty. Run with --update-settings."
  [[ "$SOURCE_PATH" == /* ]] || die \
    "Saved source path must be absolute. Run the script manually to update settings."
  [[ -d "$SOURCE_PATH" ]] || die "Source folder does not exist: $SOURCE_PATH"
  validate_remote_name "$REMOTE_NAME"
  [[ -n "$REMOTE_PATH" ]] || die "Remote path is empty."
  validate_schedule_time "$SCHEDULE_TIME"
  validate_soak_minutes "$SOAK_MINUTES"
  "$RCLONE_BIN" listremotes 2>/dev/null | grep -Fxq "${REMOTE_NAME}:" || \
    die "rclone remote '${REMOTE_NAME}' is missing. Run with --update-settings."
}


# ====== 6. Keychain and Kopia repository =====================================

keychain_password() {
  security find-generic-password \
    -s "$KEYCHAIN_SERVICE" \
    -a "$KEYCHAIN_ACCOUNT" \
    -w
}

prompt_and_store_repository_password() {
  local password=""
  local confirmation=""

  password="$(prompt_secret "Kopia repository password")"
  confirmation="$(prompt_secret "Confirm Kopia repository password")"
  [[ -n "$password" ]] || die "Kopia password cannot be empty."
  [[ "$password" == "$confirmation" ]] || die "Kopia passwords do not match."

  security add-generic-password -U \
    -s "$KEYCHAIN_SERVICE" \
    -a "$KEYCHAIN_ACCOUNT" \
    -w "$password" >/dev/null
  unset password confirmation
  success "Kopia password stored in macOS Keychain"
}

ensure_repository_password() {
  if ! keychain_password >/dev/null 2>&1; then
    [[ "$SCHEDULED_RUN" == false ]] || die \
      "Kopia password is missing from Keychain. Run the script manually."
    info "Create or enter the password for the encrypted Kopia repository."
    printf 'Save the same password in Apple Passwords: losing it makes recovery impossible.\n'
    prompt_and_store_repository_password
  fi
}

kopia_run() {
  KOPIA_PASSWORD="$(keychain_password)" "$KOPIA_BIN" \
    --config-file="$KOPIA_CONFIG_FILE" "$@"
}

repository_remote_spec() {
  printf '%s:%s' "$REMOTE_NAME" "$REMOTE_PATH"
}

connect_or_create_repository() {
  local action=""

  info "Kopia repository"
  printf 'Remote location: %s\n' "$(repository_remote_spec)"
  action="$(prompt_value "Create a new repository or connect to an existing one? (create/connect)" "create")"

  case "$action" in
    create|c|C)
      kopia_run repository create rclone \
        --rclone-exe="$RCLONE_BIN" \
        --remote-path="$(repository_remote_spec)"
      ;;
    connect|e|E)
      kopia_run repository connect rclone \
        --rclone-exe="$RCLONE_BIN" \
        --remote-path="$(repository_remote_spec)"
      ;;
    *)
      die "Choose either 'create' or 'connect'."
      ;;
  esac
}

ensure_repository_connection() {
  local backup_config=""

  ensure_repository_password

  if [[ "$REPOSITORY_CONNECTION_CHANGED" == true && -f "$KOPIA_CONFIG_FILE" ]]; then
    backup_config="$KOPIA_CONFIG_FILE.previous.$(date '+%Y%m%d%H%M%S')"
    mv "$KOPIA_CONFIG_FILE" "$backup_config"
    warn "Remote repository changed. Previous Kopia connection saved at $backup_config"
  fi

  if [[ -f "$KOPIA_CONFIG_FILE" ]] && kopia_run repository status >/dev/null 2>&1; then
    success "Connected to the existing Kopia repository"
  else
    [[ "$SCHEDULED_RUN" == false && "$RESTORE_MODE" == false ]] || die \
      "Kopia repository is not connected. Run the script manually."
    [[ -f "$KOPIA_CONFIG_FILE" ]] && mv \
      "$KOPIA_CONFIG_FILE" "$KOPIA_CONFIG_FILE.invalid.$(date '+%Y%m%d%H%M%S')"
    connect_or_create_repository
  fi

  if [[ "$RESTORE_MODE" == false ]]; then
    kopia_run policy set --global \
      --keep-latest=0 \
      --keep-hourly=0 \
      --keep-daily=14 \
      --keep-weekly=8 \
      --keep-monthly=12 \
      --keep-annual=0 \
      --ignore-identical-snapshots=true >/dev/null
    success "Retention policy is active: 14 daily, 8 weekly, 12 monthly"
  fi
}


# ====== 7. Immediate and scheduled backup ====================================

acquire_backup_lock() {
  if ! mkdir "$LOCK_DIR" 2>/dev/null; then
    die "Another backup or restore appears to be running. If it is not, remove $LOCK_DIR"
  fi
  trap 'cleanup_operation' EXIT
}

cleanup_operation() {
  if [[ -n "$RESTORE_STAGING_DIR" && \
        "$RESTORE_STAGING_DIR" == "$APP_DIR"/restore-staging.* && \
        -d "$RESTORE_STAGING_DIR" ]]; then
    rm -rf "$RESTORE_STAGING_DIR"
  fi
  rmdir "$LOCK_DIR" 2>/dev/null || true
}

source_fingerprint() {
  find "$SOURCE_PATH" -type f -exec stat -f '%N|%z|%m' {} + 2>/dev/null | \
    LC_ALL=C sort | shasum -a 256 | awk '{ print $1 }'
}

wait_for_source_after_wake() {
  local before=""
  local after=""
  local attempt=1
  local soak_seconds=$((SOAK_MINUTES * 60))

  before="$(source_fingerprint)"
  if (( soak_seconds > 0 )); then
    info "Scheduled wake-up soak: waiting $SOAK_MINUTES minute(s)"
    sleep "$soak_seconds"
  else
    info "Scheduled wake-up soak disabled; checking a $SOURCE_QUIET_SECONDS-second quiet window"
    sleep "$SOURCE_QUIET_SECONDS"
  fi
  after="$(source_fingerprint)"

  [[ "$before" == "$after" ]] && {
    success "Source tree remained stable during the soak"
    return 0
  }

  warn "Source tree changed during the soak; waiting for a quiet window."
  before="$after"
  while (( attempt <= SOURCE_QUIET_MAX_ATTEMPTS )); do
    sleep "$SOURCE_QUIET_SECONDS"
    after="$(source_fingerprint)"
    if [[ "$before" == "$after" ]]; then
      success "Source tree is stable after $SOURCE_QUIET_SECONDS seconds"
      return 0
    fi
    warn "Source is still changing (quiet check $attempt/$SOURCE_QUIET_MAX_ATTEMPTS)."
    before="$after"
    attempt=$((attempt + 1))
  done

  die "Source did not become stable; scheduled backup was aborted to avoid a mixed snapshot."
}

wait_for_remote_after_wake() {
  local attempt=1

  while (( attempt <= REMOTE_MAX_ATTEMPTS )); do
    if "$RCLONE_BIN" lsd "${REMOTE_NAME}:" --max-depth 1 >/dev/null 2>&1; then
      success "MEGA remote is reachable"
      return 0
    fi
    warn "MEGA remote is not reachable (attempt $attempt/$REMOTE_MAX_ATTEMPTS)."
    (( attempt < REMOTE_MAX_ATTEMPTS )) && sleep "$REMOTE_RETRY_SECONDS"
    attempt=$((attempt + 1))
  done

  die "MEGA remote did not become reachable; scheduled backup was not started."
}

record_backup_success() {
  local temporary_file="$STATE_FILE.tmp"
  local run_mode="manual"
  [[ "$SCHEDULED_RUN" == true ]] && run_mode="scheduled"

  umask 077
  {
    printf '# Generated by %s.\n' "$APP_NAME"
    printf 'LAST_BACKUP_SUCCESS_EPOCH=%q\n' "$(date '+%s')"
    printf 'LAST_BACKUP_SUCCESS_AT=%q\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    printf 'LAST_BACKUP_SOURCE=%q\n' "$SOURCE_PATH"
    printf 'LAST_BACKUP_MODE=%q\n' "$run_mode"
  } > "$temporary_file"
  mv "$temporary_file" "$STATE_FILE"
  chmod 600 "$STATE_FILE"
}

run_backup() {
  local fingerprint_before=""
  local fingerprint_after=""

  acquire_backup_lock
  info "Starting encrypted backup"
  printf 'Source: %s\n' "$SOURCE_PATH"
  printf 'Destination: %s\n' "$(repository_remote_spec)"

  fingerprint_before="$(source_fingerprint)"
  kopia_run snapshot create "$SOURCE_PATH"
  fingerprint_after="$(source_fingerprint)"

  if [[ "$fingerprint_before" != "$fingerprint_after" ]]; then
    warn "Source changed while Kopia was reading it; creating one follow-up snapshot."
    kopia_run snapshot create "$SOURCE_PATH"
  fi

  record_backup_success
  success "Backup completed at $(date '+%Y-%m-%d %H:%M:%S')"

  if [[ "$VERIFY_AFTER_BACKUP" == true ]]; then
    info "Verifying all files in the repository"
    kopia_run snapshot verify --verify-files-percent=100
    success "Repository verification completed"
  fi
}

run_restore() {
  local overwrite_existing=false

  acquire_backup_lock
  info "Restore from the latest snapshot"
  printf 'Source history: %s\n' "$SOURCE_PATH"
  printf 'Restore destination: %s\n' "$SOURCE_PATH"
  warn "Restore mode writes directly into the configured source directory."
  warn "Close Obsidian and make sure iCloud has finished synchronizing first."

  if confirm "Overwrite existing files and symlinks with snapshot versions?"; then
    overwrite_existing=true
    warn "Existing files may be replaced with older versions from the latest snapshot."
    printf 'Files created after that snapshot will not be deleted.\n'
  else
    printf 'Mode: restore missing files and symlinks only; existing ones will be skipped.\n'
  fi

  confirm "Start restore from the latest snapshot now?" || {
    printf 'Restore cancelled. No files were changed.\n'
    return 0
  }

  if [[ "$overwrite_existing" == true ]]; then
    kopia_run snapshot restore "$SOURCE_PATH" "$SOURCE_PATH" \
      --snapshot-time=latest \
      --overwrite-files \
      --overwrite-directories \
      --overwrite-symlinks \
      --write-files-atomically
  else
    command -v rsync >/dev/null 2>&1 || die "macOS rsync utility was not found."
    RESTORE_STAGING_DIR="$(mktemp -d "$APP_DIR/restore-staging.XXXXXX")"
    chmod 700 "$RESTORE_STAGING_DIR"
    info "Restoring the latest snapshot into a temporary staging directory"
    kopia_run snapshot restore "$SOURCE_PATH" "$RESTORE_STAGING_DIR" \
      --snapshot-time=latest \
      --write-files-atomically
    info "Copying only missing files and symlinks into the configured source"
    rsync -a \
      --ignore-existing \
      --omit-dir-times \
      --no-perms \
      --no-owner \
      --no-group \
      "$RESTORE_STAGING_DIR/" "$SOURCE_PATH/"
  fi

  success "Restore from the latest snapshot completed"
}


# ====== 8. launchd schedule ===================================================

xml_escape() {
  local value="$1"
  value="${value//&/&amp;}"
  value="${value//</&lt;}"
  value="${value//>/&gt;}"
  printf '%s' "$value"
}

write_launchd_plist() {
  local script_xml=""
  local log_xml=""
  local schedule_hour="${SCHEDULE_TIME%:*}"
  local schedule_minute="${SCHEDULE_TIME#*:}"
  schedule_hour="${schedule_hour#0}"
  schedule_minute="${schedule_minute#0}"
  [[ -n "$schedule_hour" ]] || schedule_hour=0
  [[ -n "$schedule_minute" ]] || schedule_minute=0
  script_xml="$(xml_escape "$INSTALLED_SCRIPT")"
  log_xml="$(xml_escape "$LOG_FILE")"

  mkdir -p "$HOME/Library/LaunchAgents"
  umask 077
  {
    printf '%s\n' '<?xml version="1.0" encoding="UTF-8"?>'
    printf '%s\n' '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
    printf '%s\n' '<plist version="1.0">'
    printf '%s\n' '<dict>'
    printf '  <key>Label</key><string>%s</string>\n' "$LAUNCHD_LABEL"
    printf '  <key>ProgramArguments</key><array><string>%s</string><string>--scheduled-run</string></array>\n' "$script_xml"
    printf '%s\n' '  <key>StartCalendarInterval</key>'
    printf '%s\n' '  <dict>'
    printf '    <key>Hour</key><integer>%s</integer>\n' "$schedule_hour"
    printf '    <key>Minute</key><integer>%s</integer>\n' "$schedule_minute"
    printf '%s\n' '  </dict>'
    printf '  <key>StandardOutPath</key><string>%s</string>\n' "$log_xml"
    printf '  <key>StandardErrorPath</key><string>%s</string>\n' "$log_xml"
    printf '%s\n' '</dict>'
    printf '%s\n' '</plist>'
  } > "$LAUNCHD_PLIST"
  chmod 600 "$LAUNCHD_PLIST"
  plutil -lint "$LAUNCHD_PLIST" >/dev/null
}

schedule_matches() {
  local installed_hour=""
  local installed_minute=""
  local installed_script=""
  local expected_hour="${SCHEDULE_TIME%:*}"
  local expected_minute="${SCHEDULE_TIME#*:}"
  expected_hour="${expected_hour#0}"
  expected_minute="${expected_minute#0}"
  [[ -n "$expected_hour" ]] || expected_hour=0
  [[ -n "$expected_minute" ]] || expected_minute=0
  [[ -f "$LAUNCHD_PLIST" ]] || return 1
  installed_hour="$(plutil -extract StartCalendarInterval.Hour raw "$LAUNCHD_PLIST" 2>/dev/null || true)"
  installed_minute="$(plutil -extract StartCalendarInterval.Minute raw "$LAUNCHD_PLIST" 2>/dev/null || true)"
  installed_script="$(plutil -extract ProgramArguments.0 raw "$LAUNCHD_PLIST" 2>/dev/null || true)"
  [[ "$installed_hour" == "$expected_hour" && \
     "$installed_minute" == "$expected_minute" && \
     "$installed_script" == "$INSTALLED_SCRIPT" ]]
}

ensure_schedule() {
  local domain="gui/$(id -u)"
  local service="$domain/$LAUNCHD_LABEL"

  if schedule_matches && launchctl print "$service" >/dev/null 2>&1; then
    success "Backup schedule is already installed; no duplicate was created"
    return 0
  fi

  write_launchd_plist
  launchctl bootout "$service" >/dev/null 2>&1 || true
  launchctl bootstrap "$domain" "$LAUNCHD_PLIST"
  success "Wake-aware daily schedule installed for $SCHEDULE_TIME local time"
}

next_calendar_run() {
  local schedule_time="${1:-$SCHEDULE_TIME}"
  local now_epoch=""
  local target_epoch=""
  now_epoch="$(date '+%s')"
  target_epoch="$(date -j -f '%Y-%m-%d %H:%M:%S' \
    "$(date '+%Y-%m-%d') $schedule_time:00" '+%s' 2>/dev/null)" || return 1
  if (( target_epoch <= now_epoch )); then
    target_epoch="$(date -r "$target_epoch" -v+1d '+%s')"
  fi
  date -r "$target_epoch" '+%Y-%m-%d %H:%M:%S %Z'
}

inspect_status() {
  local installed_version="not installed"
  local launch_output=""
  local launch_state="unknown"
  local launch_runs="unknown"
  local last_exit_code="unknown"
  local plist_hour=""
  local plist_minute=""
  local plist_time=""
  local service="gui/$(id -u)/$LAUNCHD_LABEL"

  info "Obsidian Vault Backup status"
  printf 'Running script version: %s\n' "$SCRIPT_VERSION"
  printf 'Application directory: %s\n' "$APP_DIR"

  if [[ -f "$INSTALLED_SCRIPT" ]]; then
    installed_version="$(extract_script_version "$INSTALLED_SCRIPT")"
    [[ -n "$installed_version" ]] || installed_version="unknown"
  fi
  printf 'Installed script version: %s\n' "$installed_version"

  if load_settings; then
    printf '\nConfiguration:\n'
    printf '  Settings file: present\n'
    printf '  Source: %s\n' "${SOURCE_PATH:-not configured}"
    if [[ -n "${SOURCE_PATH:-}" ]]; then
      if [[ "$SOURCE_PATH" != /* ]]; then
        printf '  Source status: INVALID — relative path must be updated\n'
      elif [[ -d "$SOURCE_PATH" ]]; then
        printf '  Source status: available\n'
      else
        printf '  Source status: unavailable\n'
      fi
    fi
    printf '  Repository remote: %s:%s\n' "${REMOTE_NAME:-?}" "${REMOTE_PATH:-?}"
    printf '  Daily schedule time: %s local time\n' "${SCHEDULE_TIME:-?}"
    printf '  Scheduled soak: %s minute(s)\n' "${SOAK_MINUTES:-?}"
  else
    printf '\nConfiguration: missing (%s)\n' "$SETTINGS_FILE"
  fi

  if [[ -f "$KOPIA_CONFIG_FILE" ]]; then
    printf '  Kopia connection: present\n'
  else
    printf '  Kopia connection: missing\n'
  fi

  printf '\nLast successful backup:\n'
  if [[ -f "$STATE_FILE" ]]; then
    LAST_BACKUP_SUCCESS_EPOCH=""
    LAST_BACKUP_SUCCESS_AT=""
    LAST_BACKUP_SOURCE=""
    LAST_BACKUP_MODE=""
    # shellcheck disable=SC1090
    source "$STATE_FILE"
    printf '  Time: %s\n' "${LAST_BACKUP_SUCCESS_AT:-unknown}"
    printf '  Mode: %s\n' "${LAST_BACKUP_MODE:-unknown}"
    printf '  Source: %s\n' "${LAST_BACKUP_SOURCE:-unknown}"
  else
    printf '  No state recorded yet. It will appear after the next successful backup.\n'
  fi

  printf '\nlaunchd schedule:\n'
  if [[ ! -f "$LAUNCHD_PLIST" ]]; then
    printf '  Plist: not installed\n'
    printf '  Service: not loaded\n'
    printf '  Next run: none\n'
  else
    plist_hour="$(plutil -extract StartCalendarInterval.Hour raw "$LAUNCHD_PLIST" 2>/dev/null || true)"
    plist_minute="$(plutil -extract StartCalendarInterval.Minute raw "$LAUNCHD_PLIST" 2>/dev/null || true)"
    printf '  Plist: %s\n' "$LAUNCHD_PLIST"
    if [[ -n "$plist_hour" && -n "$plist_minute" ]]; then
      printf -v plist_time '%02d:%02d' "$plist_hour" "$plist_minute"
      printf '  Calendar trigger: daily at %02d:%02d local time\n' "$plist_hour" "$plist_minute"
    else
      printf '  Calendar trigger: missing or legacy interval plist\n'
    fi

    if launch_output="$(launchctl print "$service" 2>/dev/null)"; then
      launch_state="$(printf '%s\n' "$launch_output" | awk -F'= ' '/^[[:space:]]*state =/ { print $2; exit }')"
      launch_runs="$(printf '%s\n' "$launch_output" | awk -F'= ' '/^[[:space:]]*runs =/ { print $2; exit }')"
      last_exit_code="$(printf '%s\n' "$launch_output" | awk -F'= ' '/^[[:space:]]*last exit code =/ { print $2; exit }')"
      printf '  Service: loaded\n'
      printf '  Current state: %s\n' "${launch_state:-unknown}"
      printf '  Runs: %s\n' "${launch_runs:-unknown}"
      printf '  Last exit code: %s\n' "${last_exit_code:-not reported}"
      printf '  Next calendar event: %s\n' "$(next_calendar_run "${plist_time:-$SCHEDULE_TIME}" || printf 'unknown')"
      printf '  Sleep behavior: a missed calendar event runs after the Mac wakes\n'
      printf '  Power-off behavior: a missed event waits for the next calendar day\n'
    else
      printf '  Service: plist exists but the job is not loaded\n'
      printf '  Next run: none until the job is loaded\n'
    fi
  fi

  printf '\nLogs: %s\n' "$LOG_FILE"
}


# ====== 9. Main flow ==========================================================

main() {
  parse_arguments "$@"
  validate_argument_combinations

  if [[ "$INSPECT_STATUS" == true ]]; then
    inspect_status
    exit 0
  fi

  if ! load_settings; then
    if [[ "$SCHEDULED_RUN" == true ]]; then
      die "Settings are missing: $SETTINGS_FILE"
    fi
    if [[ "$RESTORE_MODE" == true ]]; then
      die "Restore requires an existing configuration and snapshot history."
    fi
  fi
  ensure_disclaimer_acceptance

  if [[ -n "${SOURCE_PATH:-}" && "$SOURCE_PATH" != /* ]]; then
    if [[ "$SCHEDULED_RUN" == true || "$RESTORE_MODE" == true ]]; then
      die "Saved source path is relative: $SOURCE_PATH. Run the script manually to update settings."
    fi
    warn "Saved source path is relative and ambiguous: $SOURCE_PATH"
    warn "Please enter it again; it will be stored as an absolute path."
    SOURCE_PATH=""
    UPDATE_SETTINGS=true
  fi

  mkdir -p "$APP_DIR"
  chmod 700 "$APP_DIR"

  if [[ "$SCHEDULED_RUN" == true ]]; then
    add_homebrew_to_path
    KOPIA_BIN="$(command -v kopia || true)"
    RCLONE_BIN="$(command -v rclone || true)"
    [[ -x "$KOPIA_BIN" && -x "$RCLONE_BIN" ]] || die \
      "kopia or rclone is missing. Run the script manually."
    validate_effective_settings
    wait_for_remote_after_wake
    wait_for_source_after_wake
    ensure_repository_connection
    run_backup
    exit 0
  fi

  if [[ ! -f "$SETTINGS_FILE" || -z "${SOURCE_PATH:-}" ]]; then
    FIRST_CONFIGURATION=true
  fi
  install_script_copy
  ensure_dependencies

  if [[ "$FIRST_CONFIGURATION" == true || "$UPDATE_SETTINGS" == true ]]; then
    configure_settings_interactively
  fi

  load_settings || die "Settings are missing: $SETTINGS_FILE"
  if [[ "$RESTORE_MODE" == false ]]; then
    offer_shell_command
  fi
  apply_cli_overrides
  validate_effective_settings
  ensure_repository_connection

  if [[ "$RESTORE_MODE" == true ]]; then
    run_restore
    exit 0
  fi

  if [[ "$IMMEDIATE_BACKUP" == true ]]; then
    run_backup
  else
    info "Immediate backup skipped by --no-immediate-backup."
  fi

  if [[ "$INSTALL_SCHEDULE" == true ]]; then
    ensure_schedule
  fi

  info "Setup complete"
  printf 'Settings: %s\n' "$SETTINGS_FILE"
  printf 'Logs: %s\n' "$LOG_FILE"
  printf 'Run again at any time: %s\n' "$INSTALLED_SCRIPT"
  if command -v "$SHELL_COMMAND_NAME" >/dev/null 2>&1; then
    printf 'Shell command: %s\n' "$SHELL_COMMAND_NAME"
  fi
  printf 'Update settings: %s --update-settings\n' "$INSTALLED_SCRIPT"
  printf 'KopiaUI rclone executable: %s\n' "$RCLONE_BIN"
  printf 'KopiaUI remote path: %s\n' "$(repository_remote_spec)"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
